name: Production CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  deploy:
    runs-on: production
    steps:
      - uses: actions/checkout@v3
      - name: gradle bootjar
        run: |
          chmod +x ./gradlew
          ./gradlew bootjar

      - name: kill previous process
        shell: bash {0}
        run: |
          JAR_NAME="sook-backend-0.0.1-SNAPSHOT.jar"
          PROCESS_ID=$(pgrep -f "$JAR_NAME")
          if [ -n "$PROCESS_ID" ]; then
            sudo kill -9 $PROCESS_ID
            echo "구동중인 애플리케이션을 종료했습니다. (pid : $PROCESS_ID)\n"
          fi

      - name: deploy
        env:
          RUNNER_TRACKING_ID: ""
        run: |
          nohup java -jar \
          -DKAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }} \
          -DKAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }} \
          -DGOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
          -DGOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_SECRET }} \
          -DDATASOURCE_URL=${{ secrets.DATASOURCE_URL }} \
          -DDATASOURCE_USERNAME=${{ secrets.DATASOURCE_USERNAME }} \
          -DDATASOURCE_PASSWORD=${{ secrets.DATASOURCE_PASSWORD }} \
          -DACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }} \
          -DREFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }} \
          -Dserver.port=8092 \
          build/libs/sook-backend-0.0.1-SNAPSHOT.jar > ~/log.out &
